danielperna84/hass-configurator

dev.html

Starting a new
If you don't like the components modal stuff we can kill it

Latest HTML changes to new repo

---

configurator.py
dev.html

Improved UI

---

configurator.py
dev.html

I've added the new mobile concept, looks much better (though not functional yet)
Initial cleanup/beautify Search box

First merge for next release

---

changelog.txt
configurator.py
dev.html

Update to 0.1.2

---

configurator.py
dev.html

Code cleanup
Small UI tweaks
Introduction of file uploader

Commit to Dev Branch

---

configurator.py

Replace "/home/hass/.homeasssitant" by "/home/hass/.homeassistant/"

Correct note in the file

---

changelog.txt
configurator.py
dev.html
hass-poc-configurator.supervisor

Not sure if you plan on updating anymore, but I did a slight redesign and cleanup of the filebrowser sidenav

FB Sidenav Change

---

configurator.py
dev.html

Input underline color fix
Input padding fixes
Close button color to red to keep inline with the rest of Configurator

Command Modal Fixes

---

configurator.py
dev.html

One less reason to leave configurator

Added simple material icons modal

---

changelog.txt
configurator.py
dev.html

Changes for 0.1.6

---

changelog.txt
configurator.py
dev.html

- UI fix (gid add button was broken)
- Link to repository was broken
- Removed "poc" from some old links

Minor fixes

---

Dockerfile.rpi
run.sh

Added a Dockerfile to build an raspberryPi python3 image including hass-configurator

Added raspberry-pi dockerfile

---

configurator.py
settings.conf

To keep the UI cleaner I have implemented a simple filter to remove items that match the ignore list.

File Filtering

---

configurator.py

- jquery 2.1.1 --> 3.2.1
- materialdesignicons 1.8.36 --> 2.0.46
- Ace editor 1.2.6 --> 1.2.8

CDN Updates

---

configurator.py
dev.html

Figured out why modals broke with the latest version.  Please test with your enviroment

Update MaterializeCSS to v. 0.100.1

---

configurator.py
dev.html

Reverts danielperna84/hass-configurator#51
Some parts still seem broken.

Revert "Update MaterializeCSS to v. 0.100.1"

---

README.md
changelog.txt
configurator.py
dev.html

Version 0.2.4

---

configurator.py
dev.html

Update to CDN's
Added image for js-yaml
Removed card bg and hover effect for file name

CDN Update

---

configurator.py
dev.html

Reverts danielperna84/hass-configurator#86
Wrong branch

Revert 86 master

---

configurator.py
dev.html

Changed label color to match the rest of the theme
Added label and icon
Possible solution #1 for textarea (Untested)
Changed modal footer to "fixed"

Fixes for Event Observer

---

configurator.py

Simple spelling fix

---

README.md
configurator.py
settings.conf

Add ALLOWED_DOMAINS option, fixes #143

Add ALLOWED_DOMAINS option, fixes #143

---

configurator.py

Swapped documentation for `SESAME` and `HIDEHIDDEN`

Documentation fix

---

dev.html

Update the term "components" to the new "integrations"

Components to integrations
